### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by asukasmallriver** [wxyyxc1992/Backend-Boilerplate#5]
> create-spring-boot-app test1 -p com.test
开始创建新的 Spring Boot 应用位于文件夹 E:\Testing\SpringBoot\test1
初始化 test1 基于 gradle-boilerplate
开始抓取远端模板 https://github.com/wxyyxc1992/create-spring-boot-app
fs.js:950
  binding.stat(pathModule._makeLong(path));
          ^

Error: ENOENT: no such file or directory, stat 'E:\Testing\SpringBoot\test1\.tmp\gradle-boilerplate'
    at Object.fs.statSync (fs.js:950:11)
    at Object.statSync (C:\ASUKA\Tools\npm-global\node_modules\create-spring-boot-app\node_modules\graceful-fs\polyfills.js:297:22)
    at Object.copySync (C:\ASUKA\Tools\npm-global\node_modules\create-spring-boot-app\node_modules\fs-extra\lib\copy-sync\copy-sync.js:31:86)
    at C:\ASUKA\Tools\npm-global\node_modules\create-spring-boot-app\index.js:136:10
    at ChildProcess.<anonymous> (C:\ASUKA\Tools\npm-global\node_modules\create-spring-boot-app\node_modules\git-clone\index.js:42:23)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)

**Comment by wxyyxc1992** [comment]
抱歉，目前仓库正在重新规整
